Support setting a VersionTemplate
OctopusDeploy/OctoVersion pull request #66
Opened 2022-03-01 04:21 UTC by slewis74

# Background

The current mechanics of OctoVersion suit the use case for Octopus Server, in the way it versions support releases etc, but is problematic when it comes to libraries/components. In those use cases something more "traditionally SemVer" is expected by consumers. At the moment OctoVersion is fixed in its thinking about version format.

# Result

This PR looks to add support for a VersionTemplate, to allow finer control for different use cases.

Given the majority use case for this will be our library/component repositories, the default template is as follows

```
{major}.{minor}.{patch}-{preReleaseTag}.{build}
```
This results in something that those used to SemVer would recognise. It also illustrates all of the possible tokens that can be used in the template.

To get the current result that Octopus Server uses, the following template can be used
```
{major}.{minor}.{build}-{preReleaseTag}
```

## Constraints and cases considered

The contraints we are working in are:
- the build may use the OctoVersion result to tag the repo (like Octopus server does)
- tagging the repo may result in a build that calls OctoVersion (like the libraries/components will do)
- a tagged build defers the version to the tag
- a nightly build must produce a unique version number
- rebasing a branch must produce a unique version number

The uniqueness is why the build number is passed in (this is currently done via `OCTOVERSION_Patch` but would be done via `OCTOVERSION_Build` after this change).

## Nightly builds

To configure a nightly build, work on top of whichever template you already have in place. Beyond that, set the `PreReleaseTag` (`env:OCTOVERSION_PreReleaseTag`) to something like `nightly`. The string isn't important, whatever makes sense to you, it simply forces that there is a pre-release tag with that text.

2022-03-01 05:51 UTC, ryangribble commented
Does this kind of break/stretch the semver notion a bit?  Eg semver doesnt actually know about a 4th thing called "build number"?  And it explicitly says not to compare build metadata when comparing versions.  So adding this 4th concept of a build number AND using that in the `CompareTo` comparisons/calculations... is it stretching the semver concept a bit too much?

To achieve what you want couldn't you just pass in a pre release tag of `nightly.<buildcounter>` ?   

Or perhaps another way to do it would be to have a `PreReleaseTag` and `PreReleaseTagSuffix` that get appended with a period separator and only when both have a value.  This wouldn't "stretch" the semver concept by introducing a new 4th variable, it more so just adds some finesse to how a pre release tag is constructed 🤔 

> To get the current result that Octopus Server uses, the following template can be used
> {major}.{minor}.{build}-{preReleaseTag}

This also kinda sounds weird.  Obviously existing usages can continue to use the default template since they pass the build counter as `Patch` but then to be more correct they could/should be enhanced to pass the actual `Build` value but then would have to override the default template to `{Major}.Minor}.{Build}` and ignore the `Patch` value... this then means there are 2 ways to achieve the same result, which feels like it leads to confusion/inconsistency.

2022-03-01 05:52 UTC, ryangribble commented
To clarify, I think the desire to have more control over version numbers and to suit more situations such as nightly builds and other things... I'm just not sure we should create a new variable/extension to semver to achieve that...

2022-03-01 06:12 UTC, uglybugger requested changes
I'm not convinced that this is taking things in the direction we discussed.

Rather than taking it further async, I think we should arrange to pair on a refactoring of what's currently in `main`.

2022-03-01 06:12 UTC, uglybugger commented on source/OctoVersion.Core/Configuration/AppSettings.cs
> +        public string VersionTemplate { get; set; } = "{major}.{minor}.{patch}-{preReleaseTag}.{build}";
This shouldn't know anything about our internal use cases - it should be structured according to normal SemVer.

```suggestion
        public string VersionTemplate { get; set; } = "{major}.{minor}.{patch}-{preReleaseTag}.{metadata}";
```

2022-03-01 06:12 UTC, uglybugger commented on source/OctoVersion.Core/OctoVersionInfo.cs
> +        readonly VersionParser _versionParser;
This class is supposed to be the "answer" class. Why does it need to take a dependency on a service?

2022-03-01 06:12 UTC, uglybugger commented on source/OctoVersion.Core/OctoVersionInfo.cs
> +            int? patch,
Patch numbers are not optional in SemVer.

2022-03-01 06:12 UTC, uglybugger commented on source/OctoVersion.Core/VersionTemplates/VersionParser.cs
> +                if (versionString.StartsWith("v"))
I don't think we should know about magic tags here. It's either semver or it's invalid.

2022-03-01 06:12 UTC, uglybugger commented on source/OctoVersion.Core/VersionNumberCalculation/SimpleVersion.cs
> +        public SimpleVersion(int major, int minor, int? patch, int? build)
Patch numbers are not optional.

2022-03-01 06:12 UTC, uglybugger commented on source/OctoVersion.Core/VersionNumberCalculation/SimpleVersion.cs
> +            Build = build.GetValueOrDefault();
Why does this need to know about builds? It's calculated solely from the Git revision graph.

2022-03-01 06:12 UTC, uglybugger commented on source/OctoVersion.Core/VersionNumberCalculation/SimpleVersion.cs
> +        public int Build { get; }
Why does this need to know about builds? It's calculated solely from the Git revision graph.

2022-03-01 06:12 UTC, uglybugger commented on source/OctoVersion.Core/VersionNumberCalculation/VersionCalculator.cs
> +                var patch = parentIsTagged ? maxParentVersion.Patch + 1 : maxParentVersion.Patch;
I think this is distorting thing way too much for internal-specific use cases.

2022-03-01 06:12 UTC, uglybugger commented on source/OctoVersion.Core/SemanticVersion.cs
> +            if (Build != other.Build) return Build.CompareTo(other.Build);
Semantic versions don't know about builds.

2022-03-10 06:01 UTC, slewis74 commented
Closing as this isn't the path we are looking for.

2022-03-10 06:01 UTC, closed without merging